# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
    let g:dein#plugin.build = cmd
'''

# ブランチやタグを指定したいとき
# [[plugins]]
# repo = 'delphinus35/typescript-vim'
# rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
# [[plugins]]
# repo = 'elzr/vim-json'
# if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
# [[plugins]]
# repo    = 'vim-airline/vim-airline'
# depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'
#
[[plugins]]
repo = 'Shougo/vimproc'
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
[[plugins]]
repo = 'vim-scripts/VimClojure'
[[plugins]]
repo = 'Shougo/vimshell'
[[plugins]]
repo = 'scrooloose/syntastic'
[[plugins]]
repo = 'tpope/vim-surround'
[[plugins]]
repo = 'vim-scripts/The-NERD-Commenter'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
[[plugins]]
repo = 'kchmck/vim-coffee-script'
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'Shougo/neocomplete.vim'
[[plugins]]
repo = 'osyo-manga/vim-monster'
[[plugins]]
repo = 'ujihisa/repl.vim'
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
[[plugins]]
repo ='Shougo/unite.vim'
[[plugins]]
repo = 'haya14busa/vim-poweryank'
[[plugins]]
repo = 'othree/yajs.vim'
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
[[plugins]]
repo = 'fatih/vim-go'


# [[plugins]]
# repo = 'marcus/rsense'
# [[plugins]]
# repo = 'supermomonga/neocomplete-rsense.vim', {
  # \ 'autoload' : { 'insert' : 1, 'filetype' : 'ruby', } }

# [[plugins]]
# repo = 'dag/vim2hs'


